/** Direct GA4 loader. URL defaults omit room codes, query strings and referrers.
 * Served as an external same-origin script to preserve the inline-script CSP.
 * GA_MEASUREMENT_ID=off disables injection at build time.
 */
export const GA_MEASUREMENT_ID = 'G-NGHVNKN7FZ';

/** Anything under these is one page as far as a report is concerned. */
export const PRIVATE_PREFIXES = ['/room', '/join', '/invite', '/auth'] as const;

/**
 * An address safe to report.
 *
 * `/room/D53W` becomes `/room`, so a report still says how many people reached
 * a room without saying which room. A query string and a fragment go
 * altogether: an invitation carries its code in one of those too.
 */
export function publicPath(pathname: string): string {
  const path = pathname.split(/[?#]/)[0] || '/';
  return PRIVATE_PREFIXES.find((prefix) => path === prefix || path.startsWith(`${prefix}/`)) ?? path;
}

/** The loader, served from our own origin so no page needs to allow inline script. */
export function analyticsLoader(measurementId: string): string {
  if (!/^G-[A-Z0-9]+$/.test(measurementId)) throw new Error('Invalid GA4 measurement ID');
  return `// Generated by scripts/render-public-pages.ts. GA4 ${measurementId}.
(function (window, document) {
  if (location.hostname !== 'catanova.io' && location.hostname !== 'www.catanova.io') return;
  var prefixes = ${JSON.stringify([...PRIVATE_PREFIXES])};
  var path = location.pathname.split(/[?#]/)[0] || '/';
  for (var i = 0; i < prefixes.length; i++)
    if (path === prefixes[i] || path.indexOf(prefixes[i] + '/') === 0) {
      path = prefixes[i];
      break;
    }
  var layer = (window.dataLayer = window.dataLayer || []);
  // Data-layer variables alone do not override Google Analytics defaults.
  window.gtag = window.gtag || function () { layer.push(arguments); };
  function measurePath(pathname) {
    var safe = pathname.split(/[?#]/)[0] || '/';
    for (var i = 0; i < prefixes.length; i++)
      if (safe === prefixes[i] || safe.indexOf(prefixes[i] + '/') === 0) {
        safe = prefixes[i];
        break;
      }
    var values = { page_path: safe, page_location: location.origin + safe,
      page_referrer: '', page_title: safe === '/' || safe === '/guide/' ? document.title : 'Catanova' };
    window.gtag('set', values);
    layer.push(values);
  }
  measurePath(path);
  // Set safe defaults before Analytics observes a client-side navigation.
  ['pushState', 'replaceState'].forEach(function (method) {
    var original = window.history[method];
    window.history[method] = function () {
      var result = original.apply(this, arguments);
      measurePath(location.pathname);
      return result;
    };
  });
  window.addEventListener('popstate', function () { measurePath(location.pathname); });
  window.gtag('js', new Date());
  window.gtag('config', '${measurementId}', { send_page_view: true });
  var first = document.getElementsByTagName('script')[0];
  var tag = document.createElement('script');
  tag.async = true;
  tag.src = 'https://www.googletagmanager.com/gtag/js?id=${measurementId}';
  first.parentNode.insertBefore(tag, first);
})(window, document);
`;
}

export const ANALYTICS_LOADER_PATH = '/analytics.js';

export function analyticsHead(): string {
  return `<script src="${ANALYTICS_LOADER_PATH}" async></script>`;
}
