/**
 * Where the measurement goes, and what it is never allowed to see.
 *
 * Two things the pasted snippet would have got wrong here.
 *
 * A room address carries the room code: `/room/D53W`. That code is the whole
 * of what somebody needs to walk into a private lobby, so it is a credential,
 * not a page name, and it has no business in a third party's logs. Every
 * address reported goes through `publicPath` first.
 *
 * And the loader ships as a file on our own origin rather than inline in the
 * page, so the content policy keeps refusing inline script everywhere. The
 * alternative was `'unsafe-inline'` in `script-src`, which would have traded
 * the site's cross-site-scripting defence for a measurement tag.
 *
 * The container id is public by design: it names the workspace, not the
 * account. `GTM_ID=off` builds the site without any of this, which is what a
 * local build wants so the report stays about players rather than about us.
 */
export const GTM_CONTAINER = 'GTM-W4XDJ2N4';

/** Anything under these is one page as far as a report is concerned. */
export const PRIVATE_PREFIXES = ['/room', '/join', '/invite', '/auth'] as const;

/**
 * An address safe to report.
 *
 * `/room/D53W` becomes `/room`, so a report still says how many people reached
 * a room without saying which room. A query string and a fragment go
 * altogether: an invitation carries its code in one of those too.
 */
export function publicPath(pathname: string): string {
  const path = pathname.split(/[?#]/)[0] || '/';
  return PRIVATE_PREFIXES.find((prefix) => path === prefix || path.startsWith(`${prefix}/`)) ?? path;
}

/** The loader, served from our own origin so no page needs to allow inline script. */
export function analyticsLoader(container: string): string {
  if (!/^GTM-[A-Z0-9]+$/.test(container)) throw new Error('Invalid GTM container ID');
  return `// Generated by scripts/render-public-pages.ts. Container ${container}.
(function (window, document) {
  if (location.hostname !== 'catanova.io' && location.hostname !== 'www.catanova.io') return;
  var prefixes = ${JSON.stringify([...PRIVATE_PREFIXES])};
  var path = location.pathname.split(/[?#]/)[0] || '/';
  for (var i = 0; i < prefixes.length; i++)
    if (path === prefixes[i] || path.indexOf(prefixes[i] + '/') === 0) {
      path = prefixes[i];
      break;
    }
  var layer = (window.dataLayer = window.dataLayer || []);
  // Data-layer variables alone do not override Google Analytics defaults.
  window.gtag = window.gtag || function () { layer.push(arguments); };
  function measurePath(pathname) {
    var safe = pathname.split(/[?#]/)[0] || '/';
    for (var i = 0; i < prefixes.length; i++)
      if (safe === prefixes[i] || safe.indexOf(prefixes[i] + '/') === 0) {
        safe = prefixes[i];
        break;
      }
    var values = { page_path: safe, page_location: location.origin + safe,
      page_referrer: '', page_title: safe === '/' || safe === '/guide/' ? document.title : 'Catanova' };
    window.gtag('set', values);
    layer.push(values);
  }
  measurePath(path);
  // Set safe defaults before GTM observes a client-side navigation.
  ['pushState', 'replaceState'].forEach(function (method) {
    var original = window.history[method];
    window.history[method] = function () {
      var result = original.apply(this, arguments);
      measurePath(location.pathname);
      return result;
    };
  });
  window.addEventListener('popstate', function () { measurePath(location.pathname); });
  layer.push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });
  var first = document.getElementsByTagName('script')[0];
  var tag = document.createElement('script');
  tag.async = true;
  tag.src = 'https://www.googletagmanager.com/gtm.js?id=${container}';
  first.parentNode.insertBefore(tag, first);
})(window, document);
`;
}

export const ANALYTICS_LOADER_PATH = '/analytics.js';

export function analyticsHead(): string {
  return `<script src="${ANALYTICS_LOADER_PATH}" async></script>`;
}

export function analyticsNoscript(container: string): string {
  if (!/^GTM-[A-Z0-9]+$/.test(container)) throw new Error('Invalid GTM container ID');
  return `<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${container}" height="0" width="0" style="display:none;visibility:hidden" title="Google Tag Manager"></iframe></noscript>`;
}
