/** Direct GA4 loader. URL defaults omit room codes, query strings and referrers.
 * Served as an external same-origin script to preserve the inline-script CSP.
 * GA_MEASUREMENT_ID=off disables injection at build time.
 */
export const GA_MEASUREMENT_ID = 'G-NGHVNKN7FZ';

/** Anything under these is one page as far as a report is concerned. */
export const PRIVATE_PREFIXES = ['/room', '/join', '/invite', '/auth'] as const;

/**
 * The pages that carry the loader, and so the only pages that ever ask.
 *
 * Rooms, the lobby and the game are served `app.html`, which has no loader at
 * all. Somebody who starts here and opens a room leaves by history
 * navigation, which the loader watches: collection stops and the question
 * goes with it.
 */
export const MEASURED_PATHS = ['/', '/guide/', '/privacy/'] as const;

/** Where a visitor's answer is kept in this browser: `granted` or `denied`. */
export const CONSENT_STORAGE_KEY = 'catanova.analytics-consent';

/** The consent dialog's styles. Fetched only while a visitor has not answered. */
export const CONSENT_STYLESHEET = '/consent.css';

/**
 * An address safe to report.
 *
 * `/room/D53W` becomes `/room`, so a report still says how many people reached
 * a room without saying which room. A query string and a fragment go
 * altogether: an invitation carries its code in one of those too.
 */
export function publicPath(pathname: string): string {
  const path = pathname.split(/[?#]/)[0] || '/';
  return PRIVATE_PREFIXES.find((prefix) => path === prefix || path.startsWith(`${prefix}/`)) ?? path;
}

/**
 * The loader, served from our own origin so no page needs to allow inline script.
 *
 * Google Consent Mode v2 defaults every purpose to denied, and Google's tag is
 * not even fetched until the visitor answers yes: before that, nothing is sent
 * to Google at all. The answer is remembered in local storage, whose every
 * access is guarded because a private window or blocked site data can throw,
 * and the privacy page's control, which this script reveals, changes it.
 */
export function analyticsLoader(measurementId: string): string {
  if (!/^G-[A-Z0-9]+$/.test(measurementId)) throw new Error('Invalid GA4 measurement ID');
  return `// Generated by scripts/render-public-pages.ts. GA4 ${measurementId}.
(function (window, document) {
  if (location.hostname !== 'catanova.io' && location.hostname !== 'www.catanova.io') return;
  // A delayed loader may execute after the app has already navigated.
  var pages = ${JSON.stringify([...MEASURED_PATHS])};
  if (pages.indexOf(location.pathname) < 0) return;
  var prefixes = ${JSON.stringify([...PRIVATE_PREFIXES])};
  var path = location.pathname.split(/[?#]/)[0] || '/';
  for (var i = 0; i < prefixes.length; i++)
    if (path === prefixes[i] || path.indexOf(prefixes[i] + '/') === 0) {
      path = prefixes[i];
      break;
    }
  var layer = (window.dataLayer = window.dataLayer || []);
  // Data-layer variables alone do not override Google Analytics defaults.
  window.gtag = window.gtag || function () { layer.push(arguments); };
  // Consent Mode v2: denied until the visitor says otherwise, before any config.
  window.gtag('consent', 'default', { ad_storage: 'denied', ad_user_data: 'denied',
    ad_personalization: 'denied', analytics_storage: 'denied' });
  function measurePath(pathname) {
    var safe = pathname.split(/[?#]/)[0] || '/';
    for (var i = 0; i < prefixes.length; i++)
      if (safe === prefixes[i] || safe.indexOf(prefixes[i] + '/') === 0) {
        safe = prefixes[i];
        break;
      }
    var values = { page_path: safe, page_location: location.origin + safe,
      page_referrer: '', page_title: pages.indexOf(safe) >= 0 ? document.title : 'Catanova' };
    window.gtag('set', values);
    layer.push(values);
  }
  measurePath(path);
  var banner = null;
  // Closing it on purpose (an answer, or leaving for a room) must not reopen it.
  function dismiss() {
    var dialog = banner;
    banner = null;
    if (!dialog) return;
    if (dialog.open && dialog.close) dialog.close();
    if (dialog.parentNode) dialog.parentNode.removeChild(dialog);
  }
  function show(dialog) {
    if (dialog.showModal) dialog.showModal();
    else dialog.setAttribute('open', '');
    if (dialog.focus) dialog.focus();
  }
  // The question belongs to the public pages; it never follows anyone into a room.
  function leaveIfPrivate() {
    if (pages.indexOf(location.pathname) < 0) dismiss();
  }
  // Enhanced measurement can supply event-level raw URLs, overriding gtag defaults.
  // Keep this document public-only: stop before any history mutation and never
  // resume in-place (back navigation can otherwise expose a private referrer).
  function stopCollection() { window['ga-disable-${measurementId}'] = true; }
  ['pushState', 'replaceState'].forEach(function (method) {
    var original = window.history[method];
    window.history[method] = function () {
      stopCollection();
      var result = original.apply(this, arguments);
      measurePath(location.pathname);
      leaveIfPrivate();
      return result;
    };
  });
  window.addEventListener('popstate', function () { stopCollection(); leaveIfPrivate(); }, true);
  window.addEventListener('hashchange', stopCollection, true);
  var answered = null;
  function choice() {
    if (answered) return answered;
    try {
      var value = window.localStorage.getItem('${CONSENT_STORAGE_KEY}');
      return value === 'granted' || value === 'denied' ? value : null;
    } catch (error) {
      return null;
    }
  }
  var tagged = false;
  function grant() {
    window.gtag('consent', 'update', { analytics_storage: 'granted' });
    // Collection never resumes in a document that has changed address, so the
    // tag would be bytes for nothing; the next public page load measures.
    if (tagged || window['ga-disable-${measurementId}']) return;
    tagged = true;
    window.gtag('js', new Date());
    window.gtag('config', '${measurementId}', { send_page_view: true });
    var first = document.getElementsByTagName('script')[0];
    var tag = document.createElement('script');
    tag.async = true;
    tag.src = 'https://www.googletagmanager.com/gtag/js?id=${measurementId}';
    first.parentNode.insertBefore(tag, first);
  }
  function revoke() {
    window.gtag('consent', 'update', { analytics_storage: 'denied' });
    if (tagged) stopCollection();
    // Google Analytics keeps its _ga and _ga_<property> cookies on the site's domain.
    var domain = location.hostname.replace(/^www[.]/, '');
    String(document.cookie || '').split(';').forEach(function (cookie) {
      var name = cookie.split('=')[0].trim();
      if (name !== '_ga' && name.indexOf('_ga_') !== 0) return;
      document.cookie = name + '=; Max-Age=0; path=/';
      document.cookie = name + '=; Max-Age=0; path=/; domain=' + domain;
    });
  }
  // The privacy page's control: hidden until this script can make it work.
  function reflect() {
    var current = choice() || 'unset';
    var controls = document.querySelectorAll('[data-consent-control]');
    for (var i = 0; i < controls.length; i++) {
      controls[i].hidden = false;
      var states = controls[i].querySelectorAll('[data-consent-state]');
      for (var j = 0; j < states.length; j++)
        states[j].hidden = states[j].getAttribute('data-consent-state') !== current;
      var buttons = controls[i].querySelectorAll('[data-consent-choice]');
      for (var k = 0; k < buttons.length; k++)
        buttons[k].setAttribute('aria-pressed',
          String(buttons[k].getAttribute('data-consent-choice') === current));
    }
  }
  function choose(value) {
    answered = value;
    try {
      window.localStorage.setItem('${CONSENT_STORAGE_KEY}', value);
    } catch (error) {}
    dismiss();
    if (value === 'granted') grant();
    else revoke();
    reflect();
  }
  function listen(button) {
    var value = button.getAttribute('data-consent-choice') === 'granted' ? 'granted' : 'denied';
    button.addEventListener('click', function () { choose(value); });
  }
  function wire() {
    var buttons = document.querySelectorAll('[data-consent-control] [data-consent-choice]');
    for (var i = 0; i < buttons.length; i++) listen(buttons[i]);
    reflect();
  }
  function ask() {
    if (choice() || pages.indexOf(location.pathname) < 0) return;
    var style = document.createElement('link');
    style.rel = 'stylesheet';
    style.href = '${CONSENT_STYLESHEET}';
    // Appear styled or not at all; unanswered means nothing is measured.
    style.onload = function () {
      if (banner || choice() || pages.indexOf(location.pathname) < 0) return;
      // A question that must be answered: a modal dialog over the page, with
      // Accept all and a quieter, equally sized Deny.
      var dialog = (banner = document.createElement('dialog'));
      dialog.className = 'consent-dialog';
      dialog.setAttribute('aria-label', 'Analytics');
      // Focusable itself, so its question is read first rather than its link.
      dialog.setAttribute('tabindex', '-1');
      var text = document.createElement('p');
      text.textContent = 'May we use Google Analytics to count visits? ' +
        'It runs only on these public pages, never in your games. ';
      var more = document.createElement('a');
      more.href = '/privacy/';
      more.textContent = 'Privacy';
      text.appendChild(more);
      var actions = document.createElement('div');
      actions.className = 'consent-actions';
      [['denied', 'Deny'], ['granted', 'Accept all']].forEach(function (option) {
        var button = document.createElement('button');
        button.type = 'button';
        button.setAttribute('data-consent-choice', option[0]);
        button.textContent = option[1];
        button.addEventListener('click', function () { choose(option[0]); });
        actions.appendChild(button);
      });
      dialog.appendChild(text);
      dialog.appendChild(actions);
      // Escape does not close it: it waits for an answer.
      dialog.addEventListener('cancel', function (event) { event.preventDefault(); });
      // Some browsers close a modal on Escape regardless; unanswered, it opens again.
      dialog.addEventListener('close', function () {
        if (banner === dialog && !choice()) show(dialog);
      });
      document.body.appendChild(dialog);
      show(dialog);
    };
    document.head.appendChild(style);
  }
  if (choice() === 'granted') grant();
  function ready() {
    wire();
    ask();
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', ready);
  else ready();
})(window, document);
`;
}

export const ANALYTICS_LOADER_PATH = '/analytics.js';

export function analyticsHead(): string {
  return `<script src="${ANALYTICS_LOADER_PATH}" async></script>`;
}
