/**
 * The bot's memory between turns.
 *
 * Jev answers one question at a time and nothing it returns carries over to the
 * next call, so a bot that only ever asked "what now?" would restart its
 * thinking every turn and drift. This module is the fix: a small, typed plan
 * that survives across turns, is re-read into every later decision, and is
 * rewritten only when something makes it stale.
 *
 * It is deliberately not free text. Jev cannot write a sentence, so every field
 * here is either an option Jev picked from a fixed set or a number this file
 * derived from the board. `describe` then renders those fields into the line a
 * player reads in the UI, which means the explanation is generated by code and
 * can never disagree with the plan it describes.
 */

import { RESOURCE_NAMES } from '../../rules/src/index.js';
import type { Resource } from '../../rules/src/index.js';
import type { Board } from '../../rules/src/board.js';

/** The long game a bot is playing. Chosen once the opening is on the board and
 *  revisited only when the board turns against it. */
export type Archetype = 'cities' | 'expansion' | 'development' | 'trading' | 'road';

/** What the next few turns of resources are being saved for. */
export type Focus = 'settlement' | 'city' | 'road' | 'card' | 'save';

/** What the bot is worried about, which changes how it uses the robber and
 *  whether it will trade with the player in front. */
export type Threat = 'none' | 'leader-close' | 'road-contested' | 'army-contested';

export type BotPlan = {
  version: 1;
  archetype: Archetype;
  focus: Focus;
  /** The corner being built toward, so road choices have somewhere to go. */
  targetSite: number | null;
  /** Derived here, never asked: the cost of `focus` minus what is already held. */
  needs: Resource[];
  /** Derived here: resources beyond what the plan needs, safe to trade away. */
  surplus: Resource[];
  threat: Threat;
  updatedTurn: number;
  /** How many decisions this plan has survived, for the token report. */
  decisions: number;
};

export const ARCHETYPES: Record<Archetype, string> = {
  cities: 'Upgrade to cities on strong rock and hay corners, and win on card points',
  expansion: 'Spend timber and clay on roads and new settlements to claim corners early',
  development: 'Buy development cards for knights, largest army and hidden points',
  trading: 'Lean on a two-for-one harbour to convert a surplus resource into anything',
  road: 'Build a long connected road and take longest road',
};

export const FOCUS_LABEL: Record<Focus, string> = {
  settlement: 'a new settlement',
  city: 'a city',
  road: 'another road',
  card: 'a development card',
  save: 'a bigger purchase',
};

const THREAT_LABEL: Record<Threat, string> = {
  none: '',
  'leader-close': 'watching the leader close in',
  'road-contested': 'longest road is contested',
  'army-contested': 'largest army is contested',
};

export const initialPlan = (turn: number): BotPlan => ({
  version: 1,
  archetype: 'expansion',
  focus: 'settlement',
  targetSite: null,
  needs: [],
  surplus: [],
  threat: 'none',
  updatedTurn: turn,
  decisions: 0,
});

/**
 * One sentence a human can read, assembled from the typed fields above. No
 * model writes this, so it cannot describe a plan the bot is not following.
 */
export function describe(plan: BotPlan, board?: Board): string {
  const parts: string[] = [`Saving for ${FOCUS_LABEL[plan.focus]}`];
  if (plan.targetSite !== null && board) {
    const produces = cornerResources(board, plan.targetSite);
    parts[0] += produces.length
      ? ` on the ${produces.join(' and ')} corner`
      : ` at corner ${plan.targetSite + 1}`;
  }
  if (plan.needs.length) parts.push(`still needs ${plan.needs.map((r) => RESOURCE_NAMES[r]).join(' and ')}`);
  const threat = THREAT_LABEL[plan.threat];
  if (threat) parts.push(threat);
  return parts.join(', ') + '.';
}

/** The resources a corner touches, best number first, for the sentence above. */
export function cornerResources(board: Board, vertex: number): string[] {
  const corner = board.vertices[vertex];
  if (!corner) return [];
  return corner.hexes
    .map((id) => board.hexes[id])
    .filter((hex): hex is NonNullable<typeof hex> => !!hex && hex.terrain !== 'desert')
    .sort((a, b) => b.number - a.number)
    .slice(0, 2)
    .map((hex) => RESOURCE_NAMES[hex.terrain as Resource].toLowerCase());
}

/**
 * A plan is rewritten rarely, because rewriting it costs a decision and a plan
 * that changes every turn is not a plan. These are the only reasons to think
 * again: the opening is finished, the target corner was taken by someone else,
 * the plan has simply gone stale, or the game state changed shape.
 */
export function planIsStale(
  plan: BotPlan,
  context: { turn: number; targetTaken: boolean; threat: Threat; everyFewTurns?: number },
): boolean {
  if (plan.targetSite === null && plan.focus !== 'card' && plan.focus !== 'save') return true;
  if (context.targetTaken) return true;
  if (context.threat !== plan.threat) return true;
  return context.turn - plan.updatedTurn >= (context.everyFewTurns ?? 4);
}
