/**
 * Writes apps/client/src/mode-samples.data.ts: the sample game of each mode that the mode chooser draws, made by
 * apps/client/src/mode-samples.ts with the rules. Run it after a change to the rules, the boards or the samples;
 * `--check` only says whether the file is current (tests/mode-ui.test.ts checks it too).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SAMPLE_MODES, modeSample } from '../apps/client/src/mode-samples.js';

export const MODE_SAMPLES_FILE = fileURLToPath(
  new URL('../apps/client/src/mode-samples.data.ts', import.meta.url),
);

/** The file's whole text, as Prettier leaves it: the samples as one JSON string, read once when it loads. */
export function modeSamplesSource() {
  const samples = Object.fromEntries(SAMPLE_MODES.map((mode) => [mode, modeSample(mode)]));
  const json = JSON.stringify(samples).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `/**
 * Generated by scripts/mode-samples.ts from mode-samples.ts: do not edit. The sample game of each mode, by ruleset
 * id, for its picture in the mode chooser, which loads this file on its own when it opens.
 */
import type { GameView } from '../../../packages/rules/src/game.js';

export const MODE_SAMPLES: Readonly<Record<string, GameView>> = JSON.parse(
  '${json}',
);
`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const source = modeSamplesSource();
  if (process.argv.includes('--check')) {
    if (readFileSync(MODE_SAMPLES_FILE, 'utf8') !== source) {
      console.error(
        'apps/client/src/mode-samples.data.ts is out of date: run npx tsx scripts/mode-samples.ts',
      );
      process.exit(1);
    }
    console.info('The mode samples are current.');
  } else {
    writeFileSync(MODE_SAMPLES_FILE, source);
    console.info(`Wrote ${MODE_SAMPLES_FILE} (${source.length} bytes).`);
  }
}
